version: "3.7"

volumes:
  db-data:
    external: false

services:

  db:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gateway

  ev:
    image: ev
    container_name: ev
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    #ports:
    #  - "8180:8180"
    #  - "8443:8443"
    depends_on:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.apiaccess-api.entrypoints=web"
      - "traefik.http.routers.apiaccess-api.rule=Host(`ev.tetrik.com`)"
      - "traefik.http.routers.apiaccess-api-secure.entrypoints=websecure"
      - "traefik.http.routers.apiaccess-api-secure.rule=Host(`ev.tetrik.com`)"
      - "traefik.http.routers.apiaccess-api-secure.tls=true"
      - "traefik.http.routers.apiaccess-api-secure.tls.certresolver=sslResolver"
      - "traefik.http.routers.apiaccess-api-secure.service=ev"
      - "traefik.http.services.apiaccess-api.loadbalancer.server.port=8180"
